config/routes.rb
Rails.application.routes.draw do
  resources :songs
  root 'songs#index'

  get 'logout', to: 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :artist, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||=  User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
      user = User.find_by(user_name: params[:session][:user_name])
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to songs_path(user)
      else
        flash[:errors] = "Invalid login, brah"
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      flash[:bye] = "Later, brah"
      redirect_to login_path
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :set_song, only: [:show, :edit, :update, :destroy]

    def index
      @songs = Song.all
    end

    def show
    end

    def new
      @song = Song.new
    end

    def create
      @song = Song.new(song_params)
      if @song.save
        redirect_to @song
      else
        flash[:blank_song] = "You have to input something... :/"
        render :new
      end
      # song.save? ? redirect_to song : render :new
    end

    def edit
    end

    def update
      if @song.update(song_params)
        redirect_to @song
      else
        render :edit
      end
    end

    def destroy
      @song.destroy
      redirect_to @song
    end

    private

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |form| %>
  <%= form.text_field :title, placeholder: 'title' %><p>
  <%= form.text_field :artist, placeholder: 'artist' %><p>

  <%= form.submit %>
<% end %>

app/views/songs/edit.html.erb
<h2>Editing yo jam</h2>

<%= render 'form' %>

app/views/songs/index.html.erb
<h2>All Your Songs <em>Boo</em></h2>
<h3>XOXOXOXOXO: <%= current_user.user_name if current_user%> </h3>

<ul>
<% @songs.each do |song| %>
  <li><%= link_to song.title, song %></li>
<% end %>
</ul>

<%= link_to "Add a New JAM!!!", new_song_path %>
<br>
<%= link_to "Logout, brah", logout_path, method: :delete %>

<div id="bye">
  <%= flash[:later] %>
</div>

app/views/songs/new.html.erb
<h1>Add your new song <em>boo</em></h1>

<%= render 'form' %>

<div id="blank_song">
  <%= flash[:blank_song] %>
</div>

app/views/songs/show.html.erb
<h2>This is your shitty song: </h2> <h1><%= @song.title %></h1>
<h2>This is the shitty artist: </h2> <h1><%= @song.artist %></h1>

<%= link_to "Song Index", songs_path%><p>
<%= link_to "Edit this jam", edit_song_path(@song)%><p>
<%= link_to "DESTROY! DESTROY!", song_path(@song), method: :delete %>